### ISSUE TITLE
Change website to be more responsive

### ISSUE THREAD

**Issue by Paulinakhew** [Paulinakhew/paulinakhew.github.io#2]
- [what is responsive web design?](https://www.smashingmagazine.com/2011/01/guidelines-for-responsive-web-design/)
- [x] change the header so that it does not overflow on screens that are not as wide as MacBook screens
- this is how to make [responsive headers](https://www.w3schools.com/howto/howto_css_responsive_header.asp)
- [x] Change the photos to have a max width instead of having hard coded values for the sizes
- [x] Fix the overlap between the 'Try Hard' photos and the text when the screen is smaller 
- you can use css classes to divide the page into fractions
`.container{
    grid-template-columns: 1fr 1fr 1fr;
}`
- refer to [css grid layout crash course video](https://www.youtube.com/watch?v=jV8B24rSN5o) and [this html responsive web design page](https://www.w3schools.com/html/html_responsive.asp)
- you could use JavaScript to hide the inks to each section [like this](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_classes_js)
- [how to make images more responsive](https://www.w3schools.com/howto/howto_css_image_responsive.asp)

**Comment by chensokheng123** [comment]
Can I work on this?

**Comment by Paulinakhew** [comment]
Sure! Thank you in advance ☺️

**Comment by chensokheng123** [comment]
i will do my best

**Comment by chensokheng123** [comment]
Hi, I am done 70% and here it is https://youthful-swanson-d799da.netlify.com/. What do you think?

**Comment by Paulinakhew** [comment]
Hey I really like it! Thank you!! 🤩
